### ISSUE TITLE
User can't select spells even with all settings correct

### ISSUE THREAD

**Issue by geoidesic** [geoidesic/foundryvtt-actor-studio#187]
https://discord.com/channels/1343922648803049502/1343922649281335329/1410894063674064957

**Comment by Blacklands** [comment]
I believe I might have a similar issue? But it only doesn't work on some classes. I have problems with Ranger, but e.g. Sorcerer works fine. With Ranger, I somehow just get "0/0" spells in the spell selection both on character creation and level up, and no spells show up at all. 
This is with the Player's Handbook module selected as a source and all the SRD sources disabled (to avoid having everything duplicated).

Is this a known problem?

**Comment by geoidesic** [comment]
It is known now!
<img width="516" height="544" alt="Image" src="https://github.com/user-attachments/assets/e0295834-d3c8-47ed-81ce-8384dbc911f4" />

**Comment by geoidesic** [comment]
Thanks for the feedback. I'll have a look.

**Comment by geoidesic** [comment]
Looks like a 2014 / 2024 difference and I haven't catered for both yet. I will adjust the code to handle both cases. Apparently in 2014 Rangers only got spells at level 2, in 2024 they get them at level 1.

**Comment by geoidesic** [comment]
https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/2.0.17

**Comment by Blacklands** [comment]
Still doesn't seem to be quite correct. Now I get 2/2 spells at level 1, that's good, but there aren't actually any spells to select from. The list is just empty.
Also, I'm getting 2/2 cantrips as well, but Ranger doesn't actually get any cantrips at level 1.

<img width="539" height="541" alt="Image" src="https://github.com/user-attachments/assets/fdf7bfe0-d7ae-4d39-a414-78ebc801049a" />

**Comment by geoidesic** [comment]
Ok hopefully fixed now
https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/2.0.18

**Comment by Blacklands** [comment]
Well, the amount of spells is correct now. I'm still not getting any spells, unfortunately, though.

<img width="542" height="567" alt="Image" src="https://github.com/user-attachments/assets/5f074d9f-a738-4386-81f5-6691aca79b0d" />

I know that spell lists are kinda weird in Foundry. I have the Player's Handbook, so I have all the built-in SRD stuff disabled to not have duplicates all over the place. I have the Player's Handbook spells compendium set as a source for spells for Actor Studio, though.
Also, since it works for other classes, I guess something about Ranger specifically is still bugged?

**Comment by geoidesic** [comment]
Good find. That should help narrow it down tx.

**Comment by geoidesic** [comment]
I think I found the problem. 

https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/2.0.19

**Comment by Blacklands** [comment]
It's better now, but there's still issues.
I made a Ranger and advanced them until level 6.
Up to level 4, it seems to work well.
But then when advancing to level 5, when I should be able to pick 2nd-level spells, I still only get 1st-level spells to choose from.

<img width="545" height="538" alt="Image" src="https://github.com/user-attachments/assets/94cf4dc5-d1a9-41c4-bb06-90c8802e2c52" />

Then on advancing to level 6, I don't get any spells at all anymore, suddenly.

<img width="537" height="536" alt="Image" src="https://github.com/user-attachments/assets/960b67f3-dbec-45de-b8a9-bb6837ef9e66" />

**Comment by Blacklands** [comment]
Took me a while to check - but things seem to work now! Nice! :)
