### ISSUE TITLE
Latest Update Broke Module

### ISSUE THREAD

**Issue by deciusaemilius** [geoidesic/foundryvtt-actor-studio#90]
The last update seems to have completely disabled Actor Studio itself. The module no longer shows up at all under Configure Settings, and trying to use it to create an actor just leads to an error message. This happens even if I disable all other modules except Actor Studio. It worked perfectly fine before the last update and nothing else has changed on my end.

![image](https://github.com/user-attachments/assets/136fe903-6381-431d-aac2-1b27998e6d66)

![image](https://github.com/user-attachments/assets/389641b1-1b2d-4347-9ab4-70cd050bf162)
![image](https://github.com/user-attachments/assets/74d6e292-e98e-4884-9704-ed36f35a36d6)

![image](https://github.com/user-attachments/assets/fe5d01e3-c114-450c-85b0-9c9ac7187998)

![image](https://github.com/user-attachments/assets/46bb62e9-0d66-44e6-948c-02cfbb2bd550)

![image](https://github.com/user-attachments/assets/8ed4107f-fea8-411a-9865-1c343d77927e)

I went back to the previous version and everything works again.

**Comment by ShinyHobo** [comment]
I have the same issue and reverting to other versions has failed to fix it.

**Comment by geoidesic** [comment]
Fixed in 81d87493752dc5b43552c87a197ff0b027ef0d87
v1.4.3

**Comment by ShinyHobo** [comment]
After updating, I still have the issue; is there like a cache I need to clear to get this to work again?
