### ISSUE TITLE
Unable to create PC after update

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#95]
Foundry-v12.331
dnd5e-v3.3.1
AS-v1.4.6
-No other modules enabled

Attempting to create an actor after filling in all of the specifications causes an incomplete actor to be created.

https://github.com/user-attachments/assets/b9c350a2-6281-4177-abbc-df8ce6d24515

**Comment by ChobitsCrazy** [comment]
Did it a second time with full debug enabled:

https://github.com/user-attachments/assets/0481412e-7714-42aa-934b-b6904fcd9091

**Comment by geoidesic** [comment]
Hi. Please try with v1.4.7 tx.

**Comment by ChobitsCrazy** [comment]
Tried with SRD and it failed in the same way.

https://github.com/user-attachments/assets/1f678aa2-9d97-48ab-8589-f8dfdeda86a7

**Comment by ChobitsCrazy** [comment]
[localhost-1726089877843.log](https://github.com/user-attachments/files/16970566/localhost-1726089877843.log)

**Comment by geoidesic** [comment]
Hi. But did you upgrade to v 1.4.7 or not? It looks like an old bug.

**Comment by geoidesic** [comment]
I suggest uninstalling Actor Studio and reinstalling it. The version you are using looks half baked.

**Comment by ChobitsCrazy** [comment]
Still looks like I'm getting the same result =[

https://github.com/user-attachments/assets/ba2a0a37-0a48-45c1-ae33-b82d70b238e0

[localhost-1726146603412.log](https://github.com/user-attachments/files/16979817/localhost-1726146603412.log)

**Comment by geoidesic** [comment]
I haven't been able to replicate this behaviour. However, I've published a new version as your existing version is visibly broken. Try v1.4.8 and see if that sorts it out. Here's a video demoing it with SRD:


https://github.com/user-attachments/assets/e87cdc9b-1825-4c53-b173-3b8f53afefcd

**Comment by ChobitsCrazy** [comment]
Still an issue in 1.5.0

I tried a few other things as well to narrow down the issue:
1. I removed the other compendiums so it just searches the SRD items, (still an issue)
2. Tried resetting some settings, (still an issue)
3. Tested on a brand new world and it works correctly.

Not sure what is different from a new world vs my main world or what else to check on.

**Comment by geoidesic** [comment]
Thanks for trying all that. If it works on a new world that means that something in the old world is interfering with it in some way.

- The most likely candidate is other modules: always test with other modules disabled. `Find The Culprit` is a useful module for finding out which module is causing the glitch.
- If that doesn't narrow it down, you'll have to build up the new world bit by bit till it matches your old world, testing as you go and until you find the glitch.

**Comment by ChobitsCrazy** [comment]
Okay I went the opposite direction. I copied the world data to test and just started nixxing everything. What I removed that finally did the trick was the following folder:
"Data/worlds/{my world}/data/settings"

Not sure why this fixes it, and doing it on my main world is going to be a pain the ass. (attached here if you want to reference it)
[settings.zip](https://github.com/user-attachments/files/16984629/settings.zip)

Perhaps some setting or something is getting held onto between versions.

**Comment by geoidesic** [comment]
I'm not sure what I'd be able to do with that. Unfortunately we're getting into the realms of world support now which is beyond the bug fix remit. If it's working on vanilla that's about as much as I can do. If you'd like to hire me to audit your world and figure out precisely where it's gone wrong, that's possible.

What I can say is that according to the makers of foundry, that folder you mentioned stores World settings. 
You could see if Forien's Copy Environment can help you with backing up your settings.
I've attached a screenshot of the Actor Studio settings I'm using, maybe try setting your accordingly and see if that sorts it out.

![Screenshot 2024-09-13 at 17 02 40](https://github.com/user-attachments/assets/7021b5f1-b63c-4027-b7d2-1d0b9747d044)

The only thing I can think of that might be related is... I don't think I've tested what happens if you point Actor Studio at a compendium and then delete the compendium. But even then I can't see how it would affect creating characters, that should only affect which items are shown from compendiums. [Update: just tested that, it does cause a failure but it's not what you are experiencing. I've added it as a bug #97]

**Comment by geoidesic** [comment]
Any luck?

**Comment by geoidesic** [comment]
Since there's been no further response, I'm closing this issue. You can re-open it if necessary by commenting.
